<?php
// For God so loved the world, that He gave His only begotten Son
// that all who believe in Him should not perish but have everlasting life
defined( 'ABSPATH' ) or die( 'Jesus Christ is the Lord . ' );

if ( is_admin() ){ // admin actions
  add_action( 'admin_menu', 'add_oomenu_aleluya' );
  add_action( 'admin_init', 'register_oosettings_aleluya' );
} else {
  // non-admin enqueues, actions, and filters
}
function add_oomenu_aleluya() {
	//create new top-level menu
  add_menu_page('Open Orphanage Settings', '✝ Open Orphanage', 'administrator', 'oo_show_option_page1_aleluya', 'oo_show_option_page1_aleluya', "https://perffection.com/img/favicon32-aleluya.png?7aleluya" );
  add_submenu_page( 'oo_show_option_page1_aleluya', '✝ About Jesus', 'About Jesus Christ', 'administrator', 'oo_about_Jesus_aleluya', 'oo_show_about_Jesus_page_aleluya' );
	//call register settings function
	//add_action( 'admin_init', 'register_oosettings_aleluya' );
}

function register_oosettings_aleluya() { // whitelist options
  register_setting( 'oo-option-group1-aleluya', 'oo_email_address_from_address_aleluya' );
  register_setting( 'oo-option-group1-aleluya', 'oo_email_address_from_name_aleluya' );
  register_setting( 'oo-option-group1-aleluya', 'oo_administrator_logo_aleluya' );
  register_setting( 'oo-option-group1-aleluya', 'oo_sponsor_request_ifttt_event_name_aleluya');
  register_setting( 'oo-option-group1-aleluya', 'oo_ifttt_key_aleluya');
  register_setting( 'oo-option-group1-aleluya', 'oo_notify_emails_aleluya');
  //register_setting( 'oo-option-group1-aleluya', 'option_etc' );
}
function oo_show_about_Jesus_page_aleluya() {
?>
<div class="wrap">
  <h1>About Jesus Christ the Lord of Lords</h1>
<div class="arc-cont"><iframe src="https://api.arclight.org/videoPlayerUrl?refId=1_529-jf-0-0&apiSessionId=5c54ed1f415d58.03282961&player=bc.vanilla5&dtm=0&playerStyle=default" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe><style>.arc-cont{position:relative;display:block;margin:10px auto;width:100%}.arc-cont:after{padding-top:59%;display:block;content:""}.arc-cont>iframe{position:absolute;top:0;bottom:0;right:0;left:0;width:98%;height:98%;border:0}</style></div>
</div>
<?
}
//
function oo_show_option_page1_aleluya() {
?>


<div class="wrap">
<h1>✝ Open Orphanage Plugin Options</h1>
<p>Welcome to the <a href="https://openorphanage.org">Open Orphanage</a> administrator for <a href="https://wordpress.org">Wordpress</a> in <a href="https://www.jesusfilm.org/watch/jesus.html/english.html">Jesus</a> name, Hallelujah.
<form method="post" action="options.php">
<?php
settings_fields( 'oo-option-group1-aleluya' );
do_settings_sections( 'oo-option-group1-aleluya' );
?>
	<table class="form-table">
		<tr valign="top">

		<th scope="row">Change Email From Address:</th>
		  <td>
        <input type="text" name="oo_email_address_from_address_aleluya" value="<?php echo esc_attr( get_option('oo_email_address_from_address_aleluya') ); ?>" /><br/>
        <p>What email addresss do you want the emails generated by the system to appear from?</p>
      </td>
		</tr>
    <th scope="row">Change Email From Name:</th>
      <td>
        <input type="text" name="oo_email_address_from_name_aleluya" value="<?php echo esc_attr( get_option('oo_email_address_from_name_aleluya') ); ?>" /><br/>
        <p>What name do you want the emails generated by the system to appear from?</p>
      </td>
    </tr>

    <th scope="row">Emails to notify upon sponsorship requests:</th>
      <td>
        <input type="text" name="oo_notify_emails_aleluya" value="<?php echo esc_attr( get_option('oo_notify_emails_aleluya') ); ?>" /><br/>
        <p>Coma separated list of emails to notify upon sponsorship requests.</p>
      </td>
    </tr>

		<tr valign="top">
		<th scope="row">Url for Administrator Logo:</th>
		  <td>
        <input type="text" name="oo_administrator_logo_aleluya" value="<?php echo esc_attr( get_option('oo_administrator_logo_aleluya') ); ?>" />
        <p>Replace the login logo from Wordpress, for your sponsors.</p>
      </td>
		</tr>

    <tr valign="top">
    <th scope="row">IFTTT New sponsor request event name:</th>
      <td>
        <input type="text" name="oo_sponsor_request_ifttt_event_name_aleluya" value="<?php echo esc_attr( get_option('oo_sponsor_request_ifttt_event_name_aleluya') ); ?>" />
        <p>An <a href="https://www.ifttt.com">IFTTT</a> event name to fire when a new sponsor request is made.</p>
      </td>
    </tr>



    <tr valign="top">
    <th scope="row">IFTTT User webhook key:</th>
      <td>
        <input type="text" name="oo_ifttt_key_aleluya" value="<?php echo esc_attr( get_option('oo_ifttt_key_aleluya') ); ?>" />
        <p>An <a href="https://www.ifttt.com">IFTTT</a> Webhook key for IFTTT events fired.</p>
      </td>
    </tr>


  </table>
<?php submit_button(); ?>
</form>

</div>

<?php
} //end function show_oo_option_page_aleluya
?>
